version: '3.9'

services:
  main:
    container_name: test-go-main
    build: .
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:8080'
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/app/bin/migrate up && /app/bin/api" ]
  db:
    container_name: test-go-db
    image: 'postgres:13.6'
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d test_go_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
networks:
  default:
    name: test-go-network